# -*- coding: utf-8 -*-
"""gcloud-course

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f06NAAI-cPefK-2mAyeyqoi2ZiwYjI1d
"""

from google.colab import auth

auth.authenticate_user()

from google.cloud import storage

project_id = 'gcloud-course-498514'
bucket_name = 'cloud_fundament'
file_name = 'BR.json'

client_gcs = storage.Client(project=project_id)
bucket = client_gcs.get_bucket(bucket_name)
blob = bucket.blob(file_name)

file_content_str = blob.download_as_text()

print(f"File's content {file_name}")
print(file_content_str)

import json

dados_feriados = json.loads(file_content_str)
dados_feriados

from google.cloud import bigquery

client_bq = bigquery.Client(project = project_id)

consulta_pedidos = """
SELECT
  order_id, order_status, order_purchase_timestamp,
  order_estimated_delivery_date, order_delivered_customer_date
FROM `gcloud-course-498514.olist.orders`
"""

query_job = client_bq.query(consulta_pedidos)

pedidos = query_job.to_dataframe()
pedidos

consulta_atrasos = """
SELECT order_id, order_estimated_delivery_date,
order_delivered_customer_date,
DATE_DIFF(order_delivered_customer_date, order_estimated_delivery_date, DAY) AS atraso_medio_dias
FROM `gcloud-course-498514.olist.orders`
WHERE
order_delivered_customer_date IS NOT NULL
AND order_estimated_delivery_date IS NOT NULL
AND order_delivered_customer_date > order_estimated_delivery_date
ORDER BY atraso_medio_dias DESC
"""

results = client_bq.query(consulta_atrasos)
atrasos = results.to_dataframe()
atrasos

client_bq

caminho = 'gcloud-course-498514.olist.pedidos_atrados'

schema = [
    bigquery.SchemaField('order_id', 'STRING'),
    bigquery.SchemaField('order_estimated_delivery_date', 'TIMESTAMP'),
    bigquery.SchemaField('order_delivered_customer_date', 'TIMESTAMP'),
    bigquery.SchemaField('atraso_medio_dias', 'INTEGER')
]

job_config = bigquery.LoadJobConfig(
    schema = schema,
    write_disposition = "WRITE_APPEND"
)

job = client_bq.load_table_from_dataframe(atrasos, caminho, job_config = job_config)
job.result()

print(f"Tabela {caminho} carregada com sucesso!")

atrasos.to_csv('dados.csv')

client_gcs

bucket_name = 'cloud_fundament'
destino = 'dados/dados.csv'

bucket = client_gcs.get_bucket(bucket_name)
blob = bucket.blob(destino)
blob.upload_from_filename('dados.csv')